-- PREVINE QUE O OBJETO NÃO SEJA CRIADO EM DUPLICATA
CREATE DATABASE IF NOT EXISTS DB_RBONANCA_AMAZON;
USE DB_RBONANCA_AMAZON;

CREATE TABLE IF NOT EXISTS Clientes(
 -- NOME | TIPO | MODIFICADORES
    id_cliente INT PRIMARY KEY auto_increment,
    nome VARCHAR (50) NOT NULL,
    telefone VARCHAR (20),
    email VARCHAR (100),
    data_nasc DATE    
);

-- EXEMPLO APENAS PARA CONHECER O COMANDO
-- DELETE FROM Clientes
-- WHERE id >=4 AND id <=6;

